id: ICBB91E4F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T12:20:33+00:00'
last_modified: '2022-06-08T07:45:24.812702+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6840
  title: བྱ་ཐ་རྐང་དང་ཕོ་རོག་གི་སྒྲུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    A990:
      image_group_id: I3CN6842
      title: ''
      total_pages: 66
      order: 1
      base_file: A990.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
